### ISSUE TITLE
255

### ISSUE THREAD

**Issue by PHCSJC** [yoshiko2/AV_Data_Capture#102]
255

**Comment by PHCSJC** [comment]
这个其实是2个问题，上一个是重复扫描，这里说下报错日志：
[!] - 6.45% [41/635] -
[!]Making Data for   [./Carib-050517-424-FHD/050517-424-carib-1080p.mp4], the number is [Carib-050517]
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]./Carib-050517-424-FHD/050517-424-carib-1080p.mp4 Cannot catch the number :
[-]Link ./Carib-050517-424-FHD/050517-424-carib-1080p.mp4 to failed folder
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 139, in <module>
    core_main(i, getNumber(i))
  File "/downloads/sd/movies/.v/core.py", line 660, in core_main
    json_data = getDataFromJSON(number, filepath, failed_folder)  # 定义番号
  File "/downloads/sd/movies/.v/core.py", line 80, in getDataFromJSON
    json_data = json.loads(javdb.main(file_number))
  File "/downloads/sd/movies/.v/javdb.py", line 84, in main
    html = etree.fromstring(a, etree.HTMLParser())  # //table/tr[1]/td[1]/text()
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseMemoryDocument
ValueError: can only parse strings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 145, in <module>
    os.symlink(i, str(os.getcwd()) + '/' + 'failed/')
FileExistsError: [Errno 17] File exists: './Carib-050517-424-FHD/050517-424-carib-1080p.mp4' -> '/downloads/sd/movies/.v/failed/'

**Comment by PHCSJC** [comment]
再说下我用soft_link的原因，是因为影片名是翻译成中文的，这样可以看懂，如果挪动，就会造成文件名重命名，看不懂了。

**Comment by yoshiko2** [comment]
路径太多-号了，能不能重命名只剩下050517-424，太多-号程序识别不了番号

**Comment by PHCSJC** [comment]
> 路径太多-号了，能不能重命名只剩下050517-424，太多-号程序识别不了番号

可以的，感谢，现在又有另一个错误：

[!] - 0.62% [4/636] -
[!]Making Data for   [./HEYZO-1478 淫荡黑丝女秘书丘咲爱米莉专门负责处理性欲/heyzo1478-C/heyzo1478-C.mp4], the number is [HEYZO-1478]
[-]./HEYZO-1478 淫荡黑丝女秘书丘咲爱米莉专门负责处理性欲/heyzo1478-C/heyzo1478-C.mp4 Cannot catch the number :
[-]Link ./HEYZO-1478 淫荡黑丝女秘书丘咲爱米莉专门负责处理性欲/heyzo1478-C/heyzo1478-C.mp4 to failed folder
Traceback (most recent call last):
  File "/downloads/sd/movies/.v/core.py", line 160, in smallCoverCheck
    img = Image.open(path + '/1.jpg')
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'JAV_output/丘咲エミリ/HEYZO-1478/1.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 139, in <module>
    core_main(i, getNumber(i))
  File "/downloads/sd/movies/.v/core.py", line 678, in core_main
    smallCoverCheck(path, number, imagecut, json_data['cover_small'], c_word, option, Config, filepath, failed_folder)  # 检查小封面
  File "/downloads/sd/movies/.v/core.py", line 162, in smallCoverCheck
    img = Image.open('1.jpg')
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '1.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 145, in <module>
    os.symlink(i, str(os.getcwd()) + '/' + 'failed/')
FileExistsError: [Errno 17] File exists: './HEYZO-1478 淫荡黑丝女秘书丘咲爱米莉专门负责处理性欲/heyzo1478-C/heyzo1478-C.mp4' -> '/downloads/sd/movies/.v/failed/'

**Comment by PHCSJC** [comment]
另外还发现一个问题，建立的软链接的位置也不对，比如：
lrwxrwxrwx 1 root root  127 Feb  5 16:32 JUL-038-C.mp4 -> './JUL-038......

而实际上这个文件是是在../../../JUL-038......

**Comment by PHCSJC** [comment]
再报告一个问题，昨天在在用mode=1 soft_link=0扫描时，挪动文件丢了好多，好像是把好多个文件都错误的识别成同一个番号了，然后原文件就没了。

**Comment by PHCSJC** [comment]
大佬有计划debug吗？一直在等待。

**Comment by PHCSJC** [comment]
已找到更好的替代，88
