### ISSUE TITLE
在非本地环境下无法使用？

### ISSUE THREAD

**Issue by oweaF** [yoshiko2/AV_Data_Capture#132]
1. ubuntu上用rclone挂载了个Google Drive `mkdir gd && rclone mount gd: gd &` 
2.复制AVDC到GD盘上，媒体文件也移动到AVDC的目录
3.运行 `python3 AV_Data_Capture.py` 后有以下错误
```
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 8, in <module>
    from ADC_function import *
ModuleNotFoundError: No module named 'ADC_function'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 67, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory
Original exception was:
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 8, in <module>
    from ADC_function import *
ModuleNotFoundError: No module named 'ADC_function'
```

**Comment by oweaF** [comment]
这是AVDC的文件目录
```
instance-1:~/gd/AV_Data_Capture# ls
ADC_function.py     fanza.py         ssni00064.mp4  ssni00236.mp4  ssni00331.mp4  ssni00405.mp4
AV_Data_Capture.py  fc2fans_club.py  ssni00086.mp4  ssni00262.mp4  ssni00352.mp4  ssni00415.mp4
LICENSE             javbus.py        ssni00112.mp4  ssni00286.mp4  ssni00353.mp4  update_check.json
README.md           javdb.py         ssni00138.mp4  ssni00289.mp4  ssni00373.mp4
avsox.py            mgstage.py       ssni00161.mp4  ssni00308.mp4  ssni00374.mp4
config.ini          ofje00172.mp4    ssni00186.mp4  ssni00310.mp4  ssni00385.mp4
core.py             readme           ssni00213.mp4  ssni00330.mp4  ssni00395.mp4
```

**Comment by yoshiko2** [comment]
这是webdav吗

**Comment by oweaF** [comment]
不是webdav，是通过rclone挂载了一块Google Drive到本地。
上面的报错是我把AVDC复制（上传）到了挂载的目录里出现的
问题是，在挂载的环境下主程序没办法调用程序的其他部件

**Comment by oweaF** [comment]
如果我把 Google Drive 挂载到AVDC目录下，可以削挂到媒体，但是这样操作不能正确的移动媒体文件到output的对应目录下。
```
├── ADC_function.py
├── AV_Data_Capture.py
├── LICENSE
├── README.md
├── avsox.py
├── config.ini
├── core.py
├── fanza.py
├── fc2fans_club.py
├── javbus.py
├── javdb.py
├── mgstage.py
├── testmedia #这个是挂载的目录
│   ├── ABP-947.mp4
│   ├── CAWD-044.mp4
│   └── SSNI-700.mp4
└── update_check.json
```
运行后或有这样的错误
`[-]./testmedia/ABP-947.mp4 Cannot catch the number :`
`[-]Move ./testmedia/ABP-947.mp4 to failed folder`
更关键的是这样子相当于把云端的文件下载下来再进行移动归类，显然是不可行的

**Comment by wzzqq** [comment]
我昨天用rclone挂载gd盘，可以正常使用，今天不知道为什么就报错了
Traceback (most recent call last):                                                
  File "AV_Data_Capture.py", line 8, in <module>                                  
    from ADC_function import *                                                    
ModuleNotFoundError: No module named 'ADC_function'

**Comment by wzzqq** [comment]
我的系统是centos的，GD盘的挂载在/gd，当我把
AVDC的文件放入/gd/1234时，运行python3 AV_Data_Capture.py时就会报错，而当我把AVDC移动到/gd/1234/123时，运行AV_Data_Capture.py，就不会报错，可以正常使用

**Comment by oweaF** [comment]
@wzzqq 你是通过什么方式挂载的？

**Comment by oweaF** [comment]
@wzzqq 你是通过什么方式挂载的？

**Comment by wzzqq** [comment]
rclone挂载的

**Comment by oweaF** [comment]
你的方法可行👍

**Comment by hyc1743** [comment]
神了，这个办法
