### ISSUE TITLE
2.6Release版本运行失败

### ISSUE THREAD

**Issue by PTAbabybearR** [yoshiko2/AV_Data_Capture#136]
log如下，XXXXXXXXXXXXXXXXX为日文名马赛克部分

D:\AV>AV_Data_Capture.exe "SDDE-322 「常に性交」ビキニマッサージ.mp4"
[*]================== AV Data Capture ===================
[*]                     Version 2.6
[*]======================================================
[!]Making Data for   [SDDE-322 XXXXXXXXXXXXXXXXX.mp4], the number is [SDDE-322 XXXXXXXXXXXXXXXXX]
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 119, in <module>
  File "core.py", line 662, in core_main
  File "core.py", line 80, in getDataFromJSON
  File "javdb.py", line 85, in main
IndexError: list index out of range
[788] Failed to execute script AV_Data_Capture

**Comment by yoshiko2** [comment]
XXX去掉
