### ISSUE TITLE
创建软连接失败？

### ISSUE THREAD

**Issue by tanpengsccd** [yoshiko2/AV_Data_Capture#161]
使用群晖开启WEBDAV,Mac 连接到 对应目录
Python 3.7.5 ，已经按教程pip安装依赖
配置文件如下
```
[common]
main_mode=2
failed_output_folder=/Volumes/f.h6.work/Adult
success_output_folder=/Volumes/f.h6.work/Adult
soft_link=1

[proxy]
proxy=127.0.0.1:8001
timeout=5
retry=3

[Name_Rule]
location_rule=actor+'/'+number
naming_rule=number+'-'+title

[update]
update_check=1

[media]
media_warehouse=emby
#emby or plex or kodi ,emby=jellyfin

[escape]
literals=\()
folders="/Volumes/f.h6.work/Adult","/Volumes/f.h6.work/Adult"

[debug_mode]
switch=1
```
-------------
运行时日志如下
```
$  Adult sudo python3 AV_Data_Capture.py
Password:
[*]================== AV Data Capture ===================
[*]                    Version 2.8.2
[*]======================================================
[+]Find 2070 movies
[!] --- Soft link mode is ENABLE! ----
[!] - 0.04% [1/2070] -
[!]Making Data for   [./Files/1Pondo 061519_861 M痴女 美月優芽.mp4], the number is [061519-861]
[+] ---Debug info---
[+]  - actor       : 美月優芽
[+]  - cover       : https://us.netcdn.space/1pondo/assets/sample/061519_861/str.jpg
[+]  - cover_small : https://us.netcdn.space/1pondo/assets/sample/061519_861/thum_b.jpg
[+]  - director    :
[+]  - imagecut    : 3
[+]  - label       : M痴女
[+]  - number      : 061519_861
[+]  - outline     : 0 characters
[+]  - release     : 2019-06-15
[+]  - runtime     : 61
[+]  - source      : avsox.py
[+]  - studio      : 一本道 ( 1pondo )
[+]  - tag         : ['']
[+]  - title       :  M痴女 美月優芽
[+]  - website     : https://avsox.host/cn/movie/c777c689997df008
[+]  - naming_rule : 061519_861- M痴女 美月優芽
[+]  - location_rule : 美月優芽/061519_861
[+] ---Debug info---
[-]./Files/1Pondo 061519_861 M痴女 美月優芽.mp4 Cannot catch the number :
[-]Link ./Files/1Pondo 061519_861 M痴女 美月優芽.mp4 to failed folder
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 142, in <module>
    core_main(i, getNumber(i))
  File "/Volumes/f.h6.work/Adult/core.py", line 689, in core_main
    pasteFileToFolder_mode2(filepath, path, multi_part, number, part, c_word)  # 移动文件
  File "/Volumes/f.h6.work/Adult/core.py", line 577, in pasteFileToFolder_mode2
    os.symlink(filepath, path + '/' + number + part + c_word + houzhui)
OSError: [Errno 45] Operation not supported: './Files/1Pondo 061519_861 M痴女 美月優芽.mp4' -> '/Volumes/f.h6.work/Adult/美月優芽/061519_861/061519_861.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 148, in <module>
    os.symlink(i, str(os.getcwd()) + '/' + failed_folder + '/')
FileNotFoundError: [Errno 2] No such file or directory: './Files/1Pondo 061519_861 M痴女 美月優芽.mp4' -> '/Volumes/f.h6.work/Adult//Volumes/f.h6.work/Adult/'
```

**Comment by tanpengsccd** [comment]
路径写错了
