### ISSUE TITLE
macOS KeyError:'folders'

### ISSUE THREAD

**Issue by 0u0u0** [yoshiko2/AV_Data_Capture#162]
求助，非常感谢
`Traceback (most recent call last):
  File "/Volumes/h/AV_Data_Capture.py", line 105, in <module>
    escape_folder = config['escape']['folders']  # 多级目录刮削需要排除的目录
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'folders'`

**Comment by yoshiko2** [comment]
cd去程序当前目录再运行

**Comment by 0u0u0** [comment]
多谢回复
