### ISSUE TITLE
使用torjan代理，总是连接不上

### ISSUE THREAD

**Issue by fayeharuna** [yoshiko2/AV_Data_Capture#172]
代理没问题，打开adc提示 
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 105, in <module>
  File "configparser.py", line 1251, in __getitem__
KeyError: 'folders'
[1692] Failed to execute script AV_Data_Capture

**Comment by yoshiko2** [comment]
需要使用http代理

**Comment by fayeharuna** [comment]
用的是http代理端口 更新到2.9莫名好了 应该不是代理的问题
