### ISSUE TITLE
3.4/3.5版本削刮部分文件时程序直接闪退

### ISSUE THREAD

**Issue by walthack** [yoshiko2/AV_Data_Capture#271]
文件名：ABP985/ DOCP232/ FCH057
程序不能自动识别重命名或者移至失败文件夹

*3.3版本下能移动文件至失败文件夹

**Comment by ltkun** [comment]
E:\porn\AV_Data_Capture-CLI-3.5-Windows>AV_Data_Capture
[*]================== AV Data Capture ===================
[*]                     Version 3.5
[*]======================================================
[+]Find 520 movies
[!] - 0.19% [1/520] -
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 132, in <module>
  File "AV_Data_Capture.py", line 67, in create_data_and_move
  File "number_parser.py", line 37, in get_number
AttributeError: 'NoneType' object has no attribute 'group'
[3252] Failed to execute script AV_Data_Capture

**Comment by chopinsun** [comment]
遇到同样错误

**Comment by walthack** [comment]
3.52貌似修正了大部分问题，先关了。
