### ISSUE TITLE
3.5.1程序直接闪退

### ISSUE THREAD

**Issue by zhujizhe** [yoshiko2/AV_Data_Capture#283]
Traceback (most recent call last):
  File "config.py", line 11, in __init__
  File "configparser.py", line 696, in read
  File "configparser.py", line 1091, in _read
configparser.DuplicateOptionError: While reading from 'config.ini' [line 30]: option 'switch' in section 'debug_mode' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 99, in <module>
  File "config.py", line 13, in __init__
  File "configparser.py", line 696, in read
  File "configparser.py", line 1091, in _read
configparser.DuplicateOptionError: While reading from 'config.ini' [line 30]: option 'switch' in section 'debug_mode' already exists
[86712] Failed to execute script AV_Data_Capture

**Comment by SharerMax** [comment]
check `config.ini` file，maybe `debug_mode` section is duplicate
