### ISSUE TITLE
求教 Mac版 提示Config file not found! Use the default settings ，如何解决？

### ISSUE THREAD

**Issue by lacumpa** [yoshiko2/AV_Data_Capture#288]
[-] Config file not found! Use the default settings
[*]================== AV Data Capture ===================
[*]                     Version 3.6                      
[*]======================================================
[-] Config file not found! Use the default settings
Traceback (most recent call last):
  File "configparser.py", line 788, in get
  File "/Users/runner/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/collections/__init__.py", line 916, in __getitem__
  File "/Users/runner/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/collections/__init__.py", line 908, in __missing__
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 127, in <module>
  File "AV_Data_Capture.py", line 8, in check_update
  File "ADC_function.py", line 42, in get_html
  File "config.py", line 39, in proxy
  File "configparser.py", line 791, in get
configparser.NoOptionError: No option 'type' in section: 'proxy'
[25961] Failed to execute script AV_Data_Capture
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by lacumpa** [comment]
Thank you for your reply. But I don't know how to do it. Could you pls guide me on this?

**Comment by lacumpa** [comment]
以下为config.ini中的设置

[common]
main_mode=1
failed_output_folder=failed
success_output_folder=JAV_output
soft_link=0

[proxy]
;proxytype: http or socks5
type=http
proxy=
timeout=10
retry=3

[Name_Rule]
location_rule='#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule=title

[update]
update_check=1

[priority]
website=javbus,javdb,fanza,xcity,mgstage,fc2,avsox,jav321,javlib

[escape]
literals=\()/
folders=failed,JAV_output

[debug_mode]
switch=0

在mac的terminal中运行config.py，提示错误

XXX:1 XXX$ python config.py
  File "config.py", line 7
    def __init__(self, path: str = "config.ini"):
                           ^
SyntaxError: invalid syntax
