### ISSUE TITLE
[BUG]3.9版本javbus无法削挂，javdb的tag削挂错误

### ISSUE THREAD

**Issue by oweaF** [yoshiko2/AV_Data_Capture#326]
这是javbus的错误
```
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 162, in <module>
  File "AV_Data_Capture.py", line 71, in create_data_and_move
  File "core.py", line 512, in core_main
  File "core.py", line 113, in get_data_from_json
KeyError: 'actor'
```
javdb的tag没有类别只有系列。eg: DASD-710

**Comment by SharpX2016** [comment]
没有类别只有系列，存在同样问题，用3.8正常
