### ISSUE TITLE
下载图片时的延迟导致视频文件被误移入failed文件夹

### ISSUE THREAD

**Issue by vamfish** [yoshiko2/AV_Data_Capture#332]
下载图片时显示 Connect retry 三次，于是自动将视频文件移入 failed 文件夹
但是随后显示 Image Downloaded，程序尝试将视频文件移入 JAV_output 文件夹时出错
是否是因为检测文件下载的部分没有考虑到可能的延迟？
### Debug Info:
```
[+] ---Debug info---
[-]Image Download :  Connect retry 1/3
[-]Image Download :  Connect retry 2/3
[-]Image Download :  Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]Move to Failed output folder
[+]Image Downloaded! JAV_output/志戸まなみ/091520_358/091520_358-poster.jpg
10
[+]Image Downloaded! JAV_output/志戸まなみ/091520_358/091520_358-fanart.jpg
[+]Wrote!            JAV_output/志戸まなみ/091520_358/091520_358.nfo
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 162, in <module>
    create_data_and_move(movie_path, conf, conf.debug())
  File "AV_Data_Capture.py", line 71, in create_data_and_move
    core_main(file_path, n_number, c)
  File "D:\GithubRepo\AV_Data_Capture\core.py", line 571, in core_main
    paste_file_to_folder(filepath, path, number, c_word, conf)
  File "D:\GithubRepo\AV_Data_Capture\core.py", line 430, in paste_file_to_folder
    os.rename(filepath, path + '/' + number + c_word + houzhui)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '.\\091520_358.mp4' -> 'JAV_output/志戸まなみ/091520_358/091520_358.mp4'
```

**Comment by vamfish** [comment]
研究了一下，发现把 imagecut 改成 1 就可以了，原本 javdb.py 中的设定是 3
