### ISSUE TITLE
4.0.2 Linux二进制与python源码运行都会出现json decoder报错

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#360]
git checkout 回退到3.9.2就一切正常，运行log如下，看起来是没有接收到JSON数据
```
root$ python3 /appdata/AV_Data_Capture/AV_Data_Capture.py
[*]================== AV Data Capture ===================
[*]                    Version 4.0.2                     
[*]======================================================
[+]Find 41 movies
[+]------------------- DEBUG MODE ON --------------------
[!] - 2.43% [1/41] -
[!]Making Data for [./shkd-914-C.mp4], the number is [shkd-914]
[+]select javbus
Traceback (most recent call last):
  File "/appdata/AV_Data_Capture/AV_Data_Capture.py", line 163, in <module>
    create_data_and_move(movie_path, conf, conf.debug())
  File "/appdata/AV_Data_Capture/AV_Data_Capture.py", line 72, in create_data_and_move
    core_main(file_path, n_number, c)
  File "/appdata/AV_Data_Capture/core.py", line 522, in core_main
    json_data = get_data_from_json(number, filepath, conf)  # 定义番号
  File "/appdata/AV_Data_Capture/core.py", line 216, in get_data_from_json
    json_data[translate_value] = translate(json_data[translate_value])
  File "/appdata/AV_Data_Capture/ADC_function.py", line 463, in translate
    translate_list = [i["trans"] for i in result.json()["sentences"]]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Feng4** [comment]
这个地方是google翻译的问题，google翻译暂时有一些问题

**Comment by Mosney** [comment]
ac547e8 后问题解决，看起来是因为代理连不上导致的
