### ISSUE TITLE
当演员为空时出错

### ISSUE THREAD

**Issue by maohhgg** [yoshiko2/AV_Data_Capture#370]
javdb现有的所有 演員为:N/A 的都不能获取，
```
[*]================== AV Data Capture ===================
[*]                    Version 4.0.3
[*]======================================================
[+]Find 5 movies
[+]------------------- DEBUG MODE ON --------------------
[!]Making Data for [./FC2PPV-1339057.mp4], the number is [FC2-1339057]
[+]select fc2
[+]select javdb
[+]select javbus
[+]select fanza
[+]select xcity
[+]select mgstage
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 163, in <module>
  File "AV_Data_Capture.py", line 72, in create_data_and_move
  File "core.py", line 522, in core_main
  File "core.py", line 113, in get_data_from_json
KeyError: 'actor'
[14447] Failed to execute script AV_Data_Capture
```

**Comment by yoshiko2** [comment]
更新4.1.1
