### ISSUE TITLE
4.3.2匹配失败后移动路径反置

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#415]
```
[*]================== AV Data Capture ===================
[*]                    Version 4.3.2                     
[*]======================================================
[+]Find 16 movies
[+]------------------- DEBUG MODE ON --------------------
[!] - 6.25% [1/16] -
[!]Making Data for [./HNDB-127/HNDB-127C.mp4], the number is [HNDB-127C]
[+]select javbus
[+]select airav
[+]select javdb
'HNDB-127C' is not in list
[+]select fanza
[+]select xcity
[+]select mgstage
[-]Movie Data not found!
[-]Move to Failed output folder
Traceback (most recent call last):
  File "shutil.py", line 788, in move
NotADirectoryError: [Errno 20] Not a directory: './HNDB-127/HNDB-127C.mp4' -> 'HNDB-127/failed/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 174, in <module>
  File "AV_Data_Capture.py", line 83, in create_data_and_move
  File "core.py", line 657, in core_main
  File "core.py", line 150, in get_data_from_json
  File "core.py", line 44, in moveFailedFolder
  File "shutil.py", line 802, in move
  File "shutil.py", line 432, in copy2
  File "shutil.py", line 261, in copyfile
IsADirectoryError: [Errno 21] Is a directory: 'HNDB-127/failed/'
[11019] Failed to execute script AV_Data_Capture

```

如上所示，失败后的移动路径应为` failed/HNDB-127`，但是脚本处理过程中会倒过来变成`'HNDB-127/failed/'`导致运行中断，目测是最近几个版本引入地错误，之前没有遇到过此类报错。  
~~以及另外一个匹配番号问题，如果C不加任何连字符紧跟在番号后面就会被识别成番号的一部分，市面上存在的许多紧跟着C作为中文字幕标记，可以考虑把番号识别方法针对跟着的C做特别识别去除。~~

**Comment by Mosney** [comment]
https://github.com/yoshiko2/AV_Data_Capture/issues/409 这个issue看起来也与这部分逻辑有关

**Comment by Mosney** [comment]
> 市面上存在的许多紧跟着C作为中文字幕标记，可以考虑把番号识别方法针对跟着的C做特别识别去除。

也发现有部分分碟是以在文件名番号后缀以A、B、C这种形式，前面针对番号后跟着C的文件做出单独判断的建议有些不妥，请忽略
