### ISSUE TITLE
macOS下无法写入图片

### ISSUE THREAD

**Issue by wyx1818** [yoshiko2/AV_Data_Capture#44]
报错信息如下

```
 wyx@PC  ~/Desktop/AV_Data_Capture-1.2  sudo ./AV_Data_Capture.py
[*]===========AV Data Capture===========
[*]             Version 1.2
[*]=====================================
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for   [./heyzo_0217_full.mp4], the number is [heyzo-0217]
[+]Image Downloaded! JAV_output/HEYZO-0217/HEYZO-0217.jpg
[+]Writeed!          JAV_output/HEYZO-0217/HEYZO-0217.nfo
Traceback (most recent call last):
  File "core.py", line 498, in <module>
    smallCoverCheck()
  File "core.py", line 192, in smallCoverCheck
    img = Image.open(path + '/1.jpg')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/Image.py", line 2822, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file 'JAV_output/HEYZO-0217/1.jpg'
[*]=====================================
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.
```

**Comment by wyx1818** [comment]
macOS下换行符貌似也有问题，第一次运行报错
```python
env: python3\r: No such file or directory
```
