### ISSUE TITLE
刮削无码影片存在错误

### ISSUE THREAD

**Issue by tyhunter** [yoshiko2/AV_Data_Capture#46]
[*]===========AV Data Capture===========
[*]             Version 1.3
[*]=====================================
[+]Find 7 movies
[!] - 14.2% [1/7] -
[!]Making Data for   [.\heyzo-2071.mp4], the number is [heyzo-2071]
Traceback (most recent call last):
  File "core.py", line 487, in <module>
  File "core.py", line 183, in smallCoverCheck
  File "site-packages\PIL\Image.py", line 2705, in open
OSError: cannot identify image file 'JAV_output/北山かんな-[2019]スキモノ巨乳上司をオフィスでハメハメ！[HEYZO-2071]/1.jpg'
[52740] Failed to execute script core
[*]=====================================
[!] - 28.5% [2/7] -
[!]Making Data for   [.\092819-001-carib.mp4], the number is [092819-001]
Traceback (most recent call last):
  File "core.py", line 487, in <module>
  File "core.py", line 183, in smallCoverCheck
  File "site-packages\PIL\Image.py", line 2705, in open
OSError: cannot identify image file 'JAV_output/美咲結衣-[2019]AV女優をあなたの自宅に宅配！[092819-001]/1.jpg'
[61884] Failed to execute script core
[*]=====================================
[!] - 42.8% [3/7] -
[!]Making Data for   [.\heyzo-2069.mp4], the number is [heyzo-2069]
Traceback (most recent call last):
  File "core.py", line 487, in <module>
  File "core.py", line 183, in smallCoverCheck
  File "site-packages\PIL\Image.py", line 2705, in open
OSError: cannot identify image file 'JAV_output/HITOMI-[2019]美痴女～美乳熟女の淫靡な誘い～[HEYZO-2069]/1.jpg'
[62064] Failed to execute script core
[*]=====================================
[!] - 57.1% [4/7] -
[!]Making Data for   [.\heyzo-2060.mp4], the number is [heyzo-2060]
Traceback (most recent call last):
  File "core.py", line 487, in <module>
  File "core.py", line 183, in smallCoverCheck
  File "site-packages\PIL\Image.py", line 2705, in open
OSError: cannot identify image file 'JAV_output/大和田なつみ-[2019]ノンストップ！！アクメ天国～グチョグチョにして欲しい ！～[HEYZO-2060]/1.jpg'
[53488] Failed to execute script core
[*]=====================================
[!] - 71.4% [5/7] -
[!]Making Data for   [.\heyzo-2093.mp4], the number is [heyzo-2093]
Traceback (most recent call last):
  File "core.py", line 487, in <module>
  File "core.py", line 183, in smallCoverCheck
  File "site-packages\PIL\Image.py", line 2705, in open
OSError: cannot identify image file 'JAV_output/宮園ももこ-[2019]地味なメガネ女子大生の巨乳を弄ぶ[HEYZO-2093]/1.jpg'
[61992] Failed to execute script core
[*]=====================================
[!] - 85.7% [6/7] -
[!]Making Data for   [.\100319_909-1pon.mp4], the number is [100319-909]
[+]Image Downloaded! JAV_output/佐伯チアキ-[2019]余裕で三連発できちゃう極上の女優佐伯チアキ[100319_909]/100319_909.jpg
[+]Writeed!          JAV_output/佐伯チアキ-[2019]余裕で三連発できちゃう極上の女優佐伯チアキ[100319_909]/100319_909.nfo
[*]=====================================
[!] - 100.% [7/7] -
[!]Making Data for   [.\092619-001-carib.mp4], the number is [092619-001]
Traceback (most recent call last):
  File "core.py", line 487, in <module>
  File "core.py", line 183, in smallCoverCheck
  File "site-packages\PIL\Image.py", line 2705, in open
OSError: cannot identify image file 'JAV_output/HITOMI,北山かんな,立花あんり,水澄ひかり-[2019]THE未公開〜敏感マゾ乳のす ごいパイズリ5〜[092619-001]/1.jpg'
[60460] Failed to execute script core
[*]=====================================
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.
[+][+]按回车键结束，你可以在结束之前查看和错误信息。

**Comment by yoshiko2** [comment]
无码片封面刮削需要日本代理
