### ISSUE TITLE
这个番号会导致报错 FileNotFoundError: [WinError 3] 系统找不到指定的路径。

### ISSUE THREAD

**Issue by lededev** [yoshiko2/AV_Data_Capture#476]
FC2-1790087

看起来是actor里出现了\\字符导致的

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 180, in <module>
  File "AV_Data_Capture.py", line 88, in create_data_and_move
  File "core.py", line 775, in core_main
  File "core.py", line 345, in create_folder
  File "os.py", line 225, in makedirs
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '\\JAV_output/BEAST☆OF☆FUCK\\u3000獣のSEX‼乱交‼中出し‼etc../[2021] 【無】【レビュー特典】現役アイドルの願望！ハードに責めて♡目隠し・こう☆そく・３P連続中出しで理性をぶっこわす‼‼‼ [FC2-1790087]'
[11180] Failed to execute script AV_Data_Capture

```

**Comment by lededev** [comment]
commit 5f9441411e93f7177e82f58badd1596393f6500f 版本运行测试后，发现故障已经排除。
