### ISSUE TITLE
javdb刮削报错

### ISSUE THREAD

**Issue by UDMark** [yoshiko2/AV_Data_Capture#494]
你好，我使用最新的4.6.4刮削，手动在浏览器中都能搜索到相应的番号，但是用软件却一直无法刮削。javbus和javdb都连不上，然后刮削第一个失败就退出了。能帮忙看一下么？
[*]================== AV Data Capture ===================
[*]                        4.6.4
[*]======================================================
[+]Enable debug
[+]Find 83 movies
[!] - 1.20% [1/83] -
[!]Making Data for [\\TOWER\AV\古川伊织\btha035.mp4], the number is [btha035]
[+]select javbus
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]HTTPSConnectionPool(host='www.dlsite.com', port=443): Max retries exceeded with url: /pro/work/=/product_id/BTHA035.html (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
'BTHA035' is not in list
list index out of range
[+]select javdb
'BTHA035' is not in list
[+]select airav
[+]select fanza
[+]select xcity
[+]select mgstage
[+]select fc2
list index out of range
[+]select avsox
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 188, in <module>
  File "AV_Data_Capture.py", line 90, in create_data_and_move
  File "core.py", line 731, in core_main
  File "core.py", line 124, in get_data_from_json
  File "multiprocessing\pool.py", line 771, in get
  File "multiprocessing\pool.py", line 125, in worker
  File "WebCrawler\avsox.py", line 87, in main
IndexError: list index out of range
[5232] Failed to execute script AV_Data_Capture

**Comment by yoshiko2** [comment]
btha-035

**Comment by UDMark** [comment]
谢谢大神，番号字母和数字之间是要加‘’-‘’
