### ISSUE TITLE
封面裁剪失败闪退

### ISSUE THREAD

**Issue by EnnawYang** [yoshiko2/AV_Data_Capture#523]
裁剪图片引用错误文件名，另外其他正常刮削的封面也没有剪裁，直接复制了一份fanart.jpg
log:  
```
[*]================== AV Data Capture ===================
[*]                        4.6.7
[*]======================================================
[+]Enable debug
[+]Find 3 movies
[!] - 33.3% [1/3] -
[!]Making Data for [X:\夏目彩春-adn-116-uncensored\adn-116-uncensored.mp4], the number is [adn-116]
[+]select javbus
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[+] ---Debug info---
[+]  - actor       : 夏目彩春
[+]  - cover       : https://www.javbus.com/pics/cover/5sw5_b.jpg
[+]  - director    :
[+]  - extrafanart :
[+]  - imagecut    : 0
[+]  - label       :
[+]  - number      : ADN-116
[+]  - outline     : 19 characters
[+]  - release     : 2017-01-15
[+]  - runtime     : 120
[+]  - series      :
[+]  - source      : javbus.py
[+]  - studio      :
[+]  - tag         : ['単体作品', '独占配信', '人妻', '不倫', '辱め', 'ハイビジョン', 'ドラマ', '多重提出する']
[+]  - title       : 再会は蜜色に染まって。-夏目彩春
[+]  - website     : https://www.javbus.com/ja/adn-116
[+]  - cover_small :
[+]  - location_rule : 夏目彩春-ADN-116-再会は蜜色に染まって。-夏目彩春
[+]  - actor_list  : ['夏目彩春']
[+]  - trailer     :
[+]  - naming_rule : ADN-116-再会は蜜色に染まって。-夏目彩春
[+] ---Debug info---
[+]Image Downloaded! output/夏目彩春-ADN-116-再会は蜜色に染まって。-夏目彩春/ADN-116-流出-fanart.jpg
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 193, in <module>
  File "AV_Data_Capture.py", line 95, in create_data_and_move
  File "core.py", line 814, in core_main
  File "core.py", line 547, in cutImage
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'output/夏目彩春-ADN-116-再会は蜜色に染まって。-夏目彩春/ADN-116-fanart.jpg'
[20372] Failed to execute script AV_Data_Capture
```

**Comment by lededev** [comment]
将config.ini改为默认目录命名方式跑这个番号是成功的。
```
[Name_Rule]
location_rule=actor+'/'+number
naming_rule=number+'-'+title
max_title_len=50
```
改成这样也是成功的。
```
[Name_Rule]
location_rule='#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule=title
max_title_len= 78
```
所以还是检查你的Name_Rule配置吧。

**Comment by lededev** [comment]
我这里没问题，没法重现这个bug，贴一下你的config.ini。

**Comment by EnnawYang** [comment]
> 我这里没问题，没法重现这个bug
> 
你测的是流出版么？


```
[common]
main_mode=1
failed_output_folder=failed
success_output_folder=output
soft_link=0
failed_move=0
auto_exit=0
transalte_to_sc=0
multi_threading=0
;actor_gender value: female(♂) or male(♀) or both(♂ ♀) or all(♂ ♀ ⚧)
actor_gender=female

[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=0
type=socks5
proxy=127.0.0.1:1085
timeout=10
retry=3
cacert_file=

[Name_Rule]
location_rule=actor+'-'+number+'-'+title
naming_rule=number+'-'+title
max_title_len=50

[update]
update_check=1

[priority]
website=javbus,javdb,airav,fanza,xcity,mgstage,fc2,avsox,dlsite,carib

[escape]
literals=\()/
folders=failed,output

[debug_mode]
switch=1

; 机器翻译
[transalte]
switch=0
;可选项 google-free,azure
engine=google-free
; azure翻译密钥
key=
; 翻译延迟
delay=1
values=title,outline

; 预告片
[trailer]
switch=0

; 用来确定是否是无码
[uncensored]
uncensored_prefix=S2M,BT,LAF,SMD


[media]
; 影片后缀
media_type=.mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso
; 字幕后缀
sub_type=.smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.txt,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml

; 水印
[watermark]
switch=0
water=2
; 左上 0, 右上 1, 右下 2， 左下 3

; 剧照
[extrafanart]
switch=0
extrafanart_folder=extrafanart
```

**Comment by lededev** [comment]
你用的什么环境？我在Win10和Ubuntu用你的config.ini和adn-116-uncensored.mp4文件名没问题啊，每次都成功。

**Comment by EnnawYang** [comment]
win10

**Comment by lededev** [comment]
你debug信息是 `[+]  - imagecut    : 0` 我这里跑是 `[+]  - imagecut    : 1`，所以执行的功能代码是不一样的，你那个条件分支的代码我没执行到。
