### ISSUE TITLE
文件夹名字太长或非法

### ISSUE THREAD

**Issue by chyaww** [yoshiko2/AV_Data_Capture#87]
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'JAV_output/長谷川しずく,倉木みお,朝倉ことみ,小嶋ジュンナ,琥珀うた,北川瞳,仁科百華,朝田ばなな,吉田花,大堀香奈,桜花えり,雫パイン,つくし（大沢つくし）,みづなれい（みずなれい）,つぼみ, あざみねね'

**Comment by yoshiko2** [comment]
ini文件中```'actor'```先替换为```''```

**Comment by chyaww** [comment]
@yoshiko2 改了还是不行，把完整的错误贴出来吧：
[!]Making Data for   [.\MIRD-098-cd1.avi], the number is [MIRD-098]
Traceback (most recent call last):
  File "core.py", line 252, in creatFolder
  File "os.py", line 211, in makedirs
  File "os.py", line 221, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'JAV_output/長谷川しずく,倉木みお,朝倉ことみ,小嶋ジュンナ,琥珀うた,北川瞳,仁科百華,朝田ばなな,吉田花,大堀香奈,桜花えり,雫パイン,つくし（大沢つくし）,みづなれい（みずなれい）,つぼみ, あざみねね'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.py", line 704, in <module>
  File "core.py", line 256, in creatFolder
  File "os.py", line 211, in makedirs
  File "os.py", line 221, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'JAV_output/長谷川しずく,倉木みお,朝倉ことみ,小嶋ジュンナ,琥珀うた,北川瞳,仁科百華,朝田ばなな,吉田花,大堀香奈,桜花えり,雫パイン,つくし（大沢つくし）,みづなれい（みずなれい）,つぼみ, あざみねね'
[1308] Failed to execute script core

**Comment by yoshiko2** [comment]
你没把actor删掉

**Comment by chyaww** [comment]
@yoshiko2 

[Name_Rule]
location_rule = '/'+number
naming_rule = number+'-'+title

配置文件这样的~格式有错误？
