### ISSUE TITLE
图片可以找到，但是提示Movie Data not Found! 1

### ISSUE THREAD

**Issue by rushbys** [yoshiko2/AV_Data_Capture#95]
This is log
[*]================== AV Data Capture ===================
[*]                     Version 2.4
[*]======================================================
[+]Find 952 movies
[!] - 0.10% [1/952] -
[!]Making Data for   [.\ABP762.mp4], the number is [ABP762]
[-]Movie Data not found!
[-]Move to Failed output folder
[+]Image Downloaded! JAV_output/華嶋れい菜//ABP762.jpg
[+]Writeed!          JAV_output/華嶋れい菜//.nfo
[-].\ABP762.mp4 Cannot catch the number :
[-]Move .\ABP762.mp4 to failed folder
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 116, in <module>
  File "core.py", line 669, in core_main
  File "core.py", line 543, in pasteFileToFolder
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '.\\ABP762.mp4' -> 'JAV_output/華嶋れい菜//ABP762.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 125, in <module>
  File "shutil.py", line 564, in move
shutil.Error: Destination path 'H:\MOScache\games\未鉴定\wating/failed/ABP762.mp4' already exists
[3504] Failed to execute script AV_Data_Capture

所有的影片文件和AV_Data_Capture.exe 放在同一个目录下。
用的版本：2.4 windows release

**Comment by yoshiko2** [comment]
看看新版本修复没
